

name: NoDocker

on: 
  workflow_dispatch:

      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Start
      run: ./Start.sh
    
  
    

  
