I'llname: Ngrok - Docker

on: 
  workflow_dispatch:
    inputs:
      ngrok:
        description: 'ngrok auth token'
        required: true
      link_iso:
        description: 'dán link iso của ae vô đây'
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install qemu-kvm -y
          sudo apt install wget curl -y
          wget -O ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -zxvf ngrok.tgz
          ./ngrok config add-authtoken "${{ github.event.inputs.ngrok }}"
          ./ngrok tcp 5900 --region ap &>/dev/null &
      - name: cài win và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          sudo mkdir /isos/
          sudo wget -O /isos/a.iso "${{ github.event.inputs.link_iso }}" &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          sudo wget -O /isos/driver.iso https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/virtio-win-0.1.240.iso &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          echo "thanh cong, ket noi bang port 8006 o trinh duyet 
          sudo kvm -cpu host,+topoext,hv_relaxed,hv_spinlocks=0x1fff,hv-passthrough,+pae,+nx,kvm=on,+svm -smp 4,cores=4 -M q35,usb=on -device usb-tablet -m 8G -device virtio-balloon-pci -vga virtio -net nic,netdev=n0,model=virtio-net-pci -netdev user,id=n0,hostfwd=tcp::3389-:3389 -boot c -device virtio-serial-pci -device virtio-rng-pci -enable-kvm -drive file=/dev/sdc,format=raw,if=none,id=nvme0 -device nvme,drive=nvme0,serial=deadbeaf1,num_queues=8 -monitor stdio -drive if=pflash,format=raw,readonly=off,file=/usr/share/ovmf/OVMF.fd -uuid e47ddb84-fb4d-46f9-b531-14bb15156336 -vnc :0 -drive file=driver.iso,media=cdrom -drive file=win11.iso,media=cdrom
 
  
         
